# This is a basic workflow to help you get started with Actions

name: TestJava

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
       # list contents or directory
      - name: List contents
        run: ls

      # Compiles classes to test 
      - name: compile classes
        working-directory: ./src/progpoeauto
        run: javac -cp "../../testresources/junit-platform-console-standalone-1.6.0.jar"  Login.java PROGPOEAUTO.java ../../test/progpoeauto/LoginTest.java ../../test/progpoeauto/PROGPOEAUTOTEST.java

      #run tests and output report 
      - name: run tests and create report 
        working-directory: ./testresources
        run: java -jar "junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class ../../test/progpoeauto/LoginTest --reports-dir ="reports"

    
